name: web3dart_ethereum
description: Implementing a web3dart connection with browser extension (Metamask etc)
version: 0.0.1
homepage: https://github.com/inveker/web3dart_ethereum

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  web3dart: ^2.4.1
  web3_ethereum:
    git: https://github.com/inveker/web3_ethereum

dev_dependencies:
  flutter_lints: ^2.0.0